export interface Currency {
  code: string;
  name: string;
  symbol: string;
  flag: string;
}

export const currencies: Currency[] = [
  { code: 'usd', name: 'United States Dollar', symbol: '$', flag: '🇺🇸' },
  { code: 'eur', name: 'Euro', symbol: '€', flag: '🇪🇺' },
  { code: 'gbp', name: 'British Pound Sterling', symbol: '£', flag: '🇬🇧' },
  { code: 'jpy', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵' },
  { code: 'cny', name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳' },
  { code: 'aud', name: 'Australian Dollar', symbol: 'A$', flag: '🇦🇺' },
  { code: 'cad', name: 'Canadian Dollar', symbol: 'C$', flag: '🇨🇦' },
  { code: 'chf', name: 'Swiss Franc', symbol: 'CHF', flag: '🇨🇭' },
  { code: 'hkd', name: 'Hong Kong Dollar', symbol: 'HK$', flag: '🇭🇰' },
  { code: 'sgd', name: 'Singapore Dollar', symbol: 'S$', flag: '🇸🇬' },
  { code: 'sek', name: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪' },
  { code: 'krw', name: 'South Korean Won', symbol: '₩', flag: '🇰🇷' },
  { code: 'nok', name: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴' },
  { code: 'nzd', name: 'New Zealand Dollar', symbol: 'NZ$', flag: '🇳🇿' },
  { code: 'inr', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳' },
  { code: 'mxn', name: 'Mexican Peso', symbol: '$', flag: '🇲🇽' },
  { code: 'twd', name: 'Taiwan Dollar', symbol: 'NT$', flag: '🇹🇼' },
  { code: 'zar', name: 'South African Rand', symbol: 'R', flag: '🇿🇦' },
  { code: 'brl', name: 'Brazilian Real', symbol: 'R$', flag: '🇧🇷' },
  { code: 'dkk', name: 'Danish Krone', symbol: 'kr', flag: '🇩🇰' },
  { code: 'pln', name: 'Polish Zloty', symbol: 'zł', flag: '🇵🇱' },
  { code: 'thb', name: 'Thai Baht', symbol: '฿', flag: '🇹🇭' },
  { code: 'idr', name: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩' },
  { code: 'huf', name: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺' },
  { code: 'czk', name: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿' },
  { code: 'ils', name: 'Israeli Shekel', symbol: '₪', flag: '🇮🇱' },
  { code: 'clp', name: 'Chilean Peso', symbol: '$', flag: '🇨🇱' },
  { code: 'php', name: 'Philippine Peso', symbol: '₱', flag: '🇵🇭' },
  { code: 'aed', name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪' },
  { code: 'cop', name: 'Colombian Peso', symbol: '$', flag: '🇨🇴' },
  { code: 'sar', name: 'Saudi Riyal', symbol: 'ر.س', flag: '🇸🇦' },
  { code: 'myr', name: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾' },
  { code: 'ron', name: 'Romanian Leu', symbol: 'lei', flag: '🇷🇴' },
  { code: 'rub', name: 'Russian Ruble', symbol: '₽', flag: '🇷🇺' },
  { code: 'ars', name: 'Argentine Peso', symbol: '$', flag: '🇦🇷' },
  { code: 'try', name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷' },
  { code: 'bgn', name: 'Bulgarian Lev', symbol: 'лв', flag: '🇧🇬' },
  { code: 'hrk', name: 'Croatian Kuna', symbol: 'kn', flag: '🇭🇷' },
  { code: 'isk', name: 'Icelandic Krona', symbol: 'kr', flag: '🇮🇸' },
  { code: 'ngn', name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬' },
  { code: 'pkr', name: 'Pakistani Rupee', symbol: '₨', flag: '🇵🇰' },
  { code: 'egp', name: 'Egyptian Pound', symbol: 'E£', flag: '🇪🇬' },
  { code: 'vnd', name: 'Vietnamese Dong', symbol: '₫', flag: '🇻🇳' },
  { code: 'uah', name: 'Ukrainian Hryvnia', symbol: '₴', flag: '🇺🇦' },
  { code: 'pab', name: 'Panamanian Balboa', symbol: 'B/.', flag: '🇵🇦' },
  { code: 'kzt', name: 'Kazakhstani Tenge', symbol: '₸', flag: '🇰🇿' },
  { code: 'qar', name: 'Qatari Riyal', symbol: 'ر.ق', flag: '🇶🇦' },
  { code: 'kes', name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪' },
  { code: 'mad', name: 'Moroccan Dirham', symbol: 'د.م.', flag: '🇲🇦' },
  { code: 'uyu', name: 'Uruguayan Peso', symbol: '$U', flag: '🇺🇾' },
  { code: 'jod', name: 'Jordanian Dinar', symbol: 'د.ا', flag: '🇯🇴' },
  { code: 'kwd', name: 'Kuwaiti Dinar', symbol: 'د.ك', flag: '🇰🇼' },
  { code: 'bhd', name: 'Bahraini Dinar', symbol: 'د.ب', flag: '🇧🇭' },
  { code: 'omr', name: 'Omani Rial', symbol: 'ر.ع.', flag: '🇴🇲' },
  { code: 'pen', name: 'Peruvian Sol', symbol: 'S/', flag: '🇵🇪' },
  { code: 'dzd', name: 'Algerian Dinar', symbol: 'د.ج', flag: '🇩🇿' },
  { code: 'bdt', name: 'Bangladeshi Taka', symbol: '৳', flag: '🇧🇩' },
  { code: 'lkr', name: 'Sri Lankan Rupee', symbol: 'Rs', flag: '🇱🇰' },
  { code: 'mmk', name: 'Myanmar Kyat', symbol: 'K', flag: '🇲🇲' },
  { code: 'ghc', name: 'Ghanaian Cedi', symbol: 'GH₵', flag: '🇬🇭' },
  { code: 'tnd', name: 'Tunisian Dinar', symbol: 'د.ت', flag: '🇹🇳' },
  { code: 'iqd', name: 'Iraqi Dinar', symbol: 'ع.د', flag: '🇮🇶' },
  { code: 'lbp', name: 'Lebanese Pound', symbol: 'ل.ل', flag: '🇱🇧' },
  { code: 'jmd', name: 'Jamaican Dollar', symbol: 'J$', flag: '🇯🇲' },
  { code: 'bnd', name: 'Brunei Dollar', symbol: 'B$', flag: '🇧🇳' },
  { code: 'bsd', name: 'Bahamian Dollar', symbol: 'B$', flag: '🇧🇸' },
  { code: 'bob', name: 'Bolivian Boliviano', symbol: 'Bs.', flag: '🇧🇴' },
  { code: 'pyg', name: 'Paraguayan Guarani', symbol: '₲', flag: '🇵🇾' },
  { code: 'gtq', name: 'Guatemalan Quetzal', symbol: 'Q', flag: '🇬🇹' },
  { code: 'hnl', name: 'Honduran Lempira', symbol: 'L', flag: '🇭🇳' },
  { code: 'nio', name: 'Nicaraguan Cordoba', symbol: 'C$', flag: '🇳🇮' },
  { code: 'crc', name: 'Costa Rican Colon', symbol: '₡', flag: '🇨🇷' },
  { code: 'dop', name: 'Dominican Peso', symbol: 'RD$', flag: '🇩🇴' },
  { code: 'ttd', name: 'Trinidad Dollar', symbol: 'TT$', flag: '🇹🇹' },
  { code: 'bbd', name: 'Barbadian Dollar', symbol: 'Bds$', flag: '🇧🇧' },
  { code: 'xcd', name: 'East Caribbean Dollar', symbol: '$', flag: '🇦🇬' },
  { code: 'awg', name: 'Aruban Florin', symbol: 'ƒ', flag: '🇦🇼' },
  { code: 'bmd', name: 'Bermudian Dollar', symbol: '$', flag: '🇧��' },
  { code: 'kyd', name: 'Cayman Islands Dollar', symbol: '$', flag: '🇰🇾' },
  { code: 'fjd', name: 'Fijian Dollar', symbol: 'FJ$', flag: '🇫🇯' },
  { code: 'pgk', name: 'Papua New Guinean Kina', symbol: 'K', flag: '🇵🇬' },
  { code: 'sbd', name: 'Solomon Islands Dollar', symbol: 'SI$', flag: '🇸🇧' },
  { code: 'top', name: 'Tongan Paʻanga', symbol: 'T$', flag: '🇹🇴' },
  { code: 'wst', name: 'Samoan Tala', symbol: 'WS$', flag: '🇼🇸' },
  { code: 'ang', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', flag: '🇨🇼' },
  { code: 'azn', name: 'Azerbaijani Manat', symbol: '₼', flag: '🇦🇿' },
  { code: 'bam', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', flag: '🇧🇦' },
  { code: 'bwp', name: 'Botswanan Pula', symbol: 'P', flag: '🇧🇼' },
  { code: 'bzd', name: 'Belize Dollar', symbol: 'BZ$', flag: '🇧🇿' },
  { code: 'cdf', name: 'Congolese Franc', symbol: 'FC', flag: '🇨🇩' },
  { code: 'etb', name: 'Ethiopian Birr', symbol: 'Br', flag: '🇪🇹' },
  { code: 'gel', name: 'Georgian Lari', symbol: '₾', flag: '🇬🇪' },
  { code: 'ghs', name: 'Ghanaian Cedi', symbol: 'GH₵', flag: '🇬🇭' },
  { code: 'gmd', name: 'Gambian Dalasi', symbol: 'D', flag: '🇬🇲' },
  { code: 'gnf', name: 'Guinean Franc', symbol: 'FG', flag: '🇬🇳' },
  { code: 'gyd', name: 'Guyanaese Dollar', symbol: 'G$', flag: '🇬🇾' },
  { code: 'htg', name: 'Haitian Gourde', symbol: 'G', flag: '🇭🇹' },
  { code: 'kgs', name: 'Kyrgystani Som', symbol: 'с', flag: '🇰🇬' },
  { code: 'khr', name: 'Cambodian Riel', symbol: '៛', flag: '🇰🇭' },
  { code: 'lak', name: 'Laotian Kip', symbol: '₭', flag: '🇱🇦' },
  { code: 'lrd', name: 'Liberian Dollar', symbol: 'L$', flag: '🇱🇷' },
  { code: 'lsl', name: 'Lesotho Loti', symbol: 'L', flag: '🇱🇸' },
  { code: 'lyd', name: 'Libyan Dinar', symbol: 'ل.د', flag: '🇱🇾' },
  { code: 'mdl', name: 'Moldovan Leu', symbol: 'L', flag: '🇲🇩' },
  { code: 'mga', name: 'Malagasy Ariary', symbol: 'Ar', flag: '🇲🇬' },
  { code: 'mkd', name: 'Macedonian Denar', symbol: 'ден', flag: '🇲🇰' },
  { code: 'mnt', name: 'Mongolian Tugrik', symbol: '₮', flag: '🇲🇳' },
  { code: 'mop', name: 'Macanese Pataca', symbol: 'MOP$', flag: '🇲🇴' },
  { code: 'mur', name: 'Mauritian Rupee', symbol: '₨', flag: '🇲🇺' },
  { code: 'mvr', name: 'Maldivian Rufiyaa', symbol: 'Rf', flag: '🇲🇻' },
  { code: 'mwk', name: 'Malawian Kwacha', symbol: 'MK', flag: '🇲🇼' },
  { code: 'mzn', name: 'Mozambican Metical', symbol: 'MT', flag: '🇲🇿' },
  { code: 'nad', name: 'Namibian Dollar', symbol: 'N$', flag: '🇳🇦' },
  { code: 'npr', name: 'Nepalese Rupee', symbol: '₨', flag: '🇳🇵' },
  { code: 'rsd', name: 'Serbian Dinar', symbol: 'дин.', flag: '🇷🇸' },
  { code: 'rwf', name: 'Rwandan Franc', symbol: 'FRw', flag: '🇷🇼' },
  { code: 'scr', name: 'Seychellois Rupee', symbol: '₨', flag: '🇸🇨' },
  { code: 'sos', name: 'Somali Shilling', symbol: 'Sh', flag: '🇸🇴' },
  { code: 'srd', name: 'Surinamese Dollar', symbol: '$', flag: '🇸🇷' },
  { code: 'std', name: 'Sao Tome Dobra', symbol: 'Db', flag: '🇸🇹' },
  { code: 'syp', name: 'Syrian Pound', symbol: '£S', flag: '🇸🇾' },
  { code: 'szl', name: 'Swazi Lilangeni', symbol: 'L', flag: '🇸🇿' },
  { code: 'tjs', name: 'Tajikistani Somoni', symbol: 'ЅМ', flag: '🇹🇯' },
  { code: 'tmt', name: 'Turkmenistani Manat', symbol: 'm', flag: '🇹🇲' },
  { code: 'tzs', name: 'Tanzanian Shilling', symbol: 'TSh', flag: '🇹🇿' },
  { code: 'ugx', name: 'Ugandan Shilling', symbol: 'USh', flag: '🇺🇬' },
  { code: 'uzs', name: 'Uzbekistan Som', symbol: 'so\'m', flag: '🇺🇿' },
  { code: 'vuv', name: 'Vanuatu Vatu', symbol: 'VT', flag: '🇻🇺' },
  { code: 'xaf', name: 'Central African CFA Franc', symbol: 'FCFA', flag: '🇨🇲' },
  { code: 'xof', name: 'West African CFA Franc', symbol: 'CFA', flag: '🇸🇳' },
  { code: 'xpf', name: 'CFP Franc', symbol: '₣', flag: '🇵🇫' },
  { code: 'yer', name: 'Yemeni Rial', symbol: '﷼', flag: '🇾🇪' },
  { code: 'zmw', name: 'Zambian Kwacha', symbol: 'ZK', flag: '🇿🇲' },
  { code: 'zwl', name: 'Zimbabwean Dollar', symbol: 'Z$', flag: '🇿🇼' },
  { code: 'afn', name: 'Afghan Afghani', symbol: '؋', flag: '🇦🇫' },
  { code: 'all', name: 'Albanian Lek', symbol: 'L', flag: '🇦🇱' },
  { code: 'amd', name: 'Armenian Dram', symbol: '֏', flag: '🇦🇲' },
  { code: 'aoa', name: 'Angolan Kwanza', symbol: 'Kz', flag: '🇦🇴' },
  { code: 'bif', name: 'Burundian Franc', symbol: 'FBu', flag: '🇧🇮' },
  { code: 'btn', name: 'Bhutanese Ngultrum', symbol: 'Nu.', flag: '🇧🇹' },
  { code: 'byn', name: 'Belarusian Ruble', symbol: 'Br', flag: '🇧🇾' },
  { code: 'kmf', name: 'Comorian Franc', symbol: 'CF', flag: '🇰🇲' },
  { code: 'cve', name: 'Cape Verdean Escudo', symbol: '$', flag: '🇨🇻' },
  { code: 'djf', name: 'Djiboutian Franc', symbol: 'Fdj', flag: '🇩🇯' },
  { code: 'ern', name: 'Eritrean Nakfa', symbol: 'Nfk', flag: '🇪🇷' },
  { code: 'irr', name: 'Iranian Rial', symbol: '﷼', flag: '🇮🇷' },
  { code: 'kpw', name: 'North Korean Won', symbol: '₩', flag: '🇰🇵' },
  { code: 'mru', name: 'Mauritanian Ouguiya', symbol: 'UM', flag: '🇲🇷' },
  { code: 'sll', name: 'Sierra Leonean Leone', symbol: 'Le', flag: '🇸🇱' },
  { code: 'ssp', name: 'South Sudanese Pound', symbol: '£', flag: '🇸🇸' },
  { code: 'vef', name: 'Venezuelan Bolivar', symbol: 'Bs', flag: '🇻🇪' },
];

export function getCurrencyByCode(code: string): Currency | undefined {
  return currencies.find(c => c.code.toLowerCase() === code.toLowerCase());
}
